create table dev_parameter (
    id bigint generated by default as identity,
    name varchar(255),
    use_yn boolean not null default 0,
    primary key (id)
)

create table tb_community (
    id bigint generated by default as identity,
    category varchar(50),
    title varchar(100),
    content text,
    content_without_html_tags text,
    author_id bigint,
    view_count bigint not null default 0,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id)
);

create table tb_file (
    id bigint generated by default as identity,
    type varchar(50),
    image_resize_type varchar(20),
    relation_type varchar(50),
    relation_id bigint,
    released boolean not null default 1,
    extension varchar(10),
    original_filename varchar(255),
    stored_filename varchar(50),
    url varchar(255),
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id)
);

create table tb_sms_certification_hist (
    id bigint generated by default as identity,
    phone_number varchar(20),
    number varchar(6),
    certified boolean default 0 not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id)
);

create table tb_tag_relation (
    id bigint generated by default as identity,
    relation_id bigint,
    relation_type varchar(50),
    tag_name varchar(20),
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id)
);

create table tb_user (
    id bigint generated by default as identity,
    login_id varchar(50),
    kakao_id varchar(50),
    google_id varchar(50),
    password varchar(255),
    email varchar(100),
    phone_number varchar(20),
    nickname varchar(50),
    image_url varchar(255),
    position varchar(50),
    refreshable boolean not null default 1,
    role varchar(255),
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id)
);

alter table if exists tb_community add constraint tb_community_idx1 unique (id, category);

alter table if exists tb_user add constraint tb_user_idx1 unique (login_id);

alter table if exists tb_user add constraint tb_user_idx2 unique (kakao_id);

alter table if exists tb_user add constraint tb_user_idx3 unique (google_id);